language: php
sudo: false
git:
  submodules: false
cache:
  directories:
    - vendor
    - $HOME/.composer
php:
  - 5.5
  - 5.6
  - 7.0
install:
  # For the git tests - TODO
  - git config --global user.email you@example.com && git config --global user.name you
  - export PATH=$PATH:~/.composer/vendor/bin
  - which php-cs-fixer || composer global require fabpot/php-cs-fixer
  - composer install
script:
  - vendor/bin/phpunit
  - php-cs-fixer fix --dry-run -v --diff src
  - php-cs-fixer fix --dry-run -v --diff tests
