language: php
sudo: false
git:
  submodules: false
php:
  - 5.5
  - 5.6
  - 7.0
install:
  # - export PATH=$PATH:~/.composer/vendor/bin
  # - composer global require fabpot/php-cs-fixer
  - composer install
  - git config --global user.email you@example.com && git config --global user.name you
script:
  - vendor/bin/phpunit
  # - php-cs-fixer fix --dry-run -v --diff src
